// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	http "net/http"

	mock "github.com/stretchr/testify/mock"

	ory "github.com/mathtrail/canvas-api/internal/ory"
)

// MockSessionValidator is an autogenerated mock type for the SessionValidator type
type MockSessionValidator struct {
	mock.Mock
}

type MockSessionValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionValidator) EXPECT() *MockSessionValidator_Expecter {
	return &MockSessionValidator_Expecter{mock: &_m.Mock}
}

// WhoAmI provides a mock function with given fields: ctx, cookies
func (_m *MockSessionValidator) WhoAmI(ctx context.Context, cookies []*http.Cookie) (*ory.Session, error) {
	ret := _m.Called(ctx, cookies)

	if len(ret) == 0 {
		panic("no return value specified for WhoAmI")
	}

	var r0 *ory.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []*http.Cookie) (*ory.Session, error)); ok {
		return rf(ctx, cookies)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []*http.Cookie) *ory.Session); ok {
		r0 = rf(ctx, cookies)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ory.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []*http.Cookie) error); ok {
		r1 = rf(ctx, cookies)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionValidator_WhoAmI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WhoAmI'
type MockSessionValidator_WhoAmI_Call struct {
	*mock.Call
}

// WhoAmI is a helper method to define mock.On call
//   - ctx context.Context
//   - cookies []*http.Cookie
func (_e *MockSessionValidator_Expecter) WhoAmI(ctx interface{}, cookies interface{}) *MockSessionValidator_WhoAmI_Call {
	return &MockSessionValidator_WhoAmI_Call{Call: _e.mock.On("WhoAmI", ctx, cookies)}
}

func (_c *MockSessionValidator_WhoAmI_Call) Run(run func(ctx context.Context, cookies []*http.Cookie)) *MockSessionValidator_WhoAmI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]*http.Cookie))
	})
	return _c
}

func (_c *MockSessionValidator_WhoAmI_Call) Return(_a0 *ory.Session, _a1 error) *MockSessionValidator_WhoAmI_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionValidator_WhoAmI_Call) RunAndReturn(run func(context.Context, []*http.Cookie) (*ory.Session, error)) *MockSessionValidator_WhoAmI_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSessionValidator creates a new instance of MockSessionValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionValidator {
	mock := &MockSessionValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
