// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockStrokePublisher is an autogenerated mock type for the StrokePublisher type
type MockStrokePublisher struct {
	mock.Mock
}

type MockStrokePublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStrokePublisher) EXPECT() *MockStrokePublisher_Expecter {
	return &MockStrokePublisher_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function with given fields: ctx, sessionID, data
func (_m *MockStrokePublisher) Publish(ctx context.Context, sessionID string, data []byte) error {
	ret := _m.Called(ctx, sessionID, data)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) error); ok {
		r0 = rf(ctx, sessionID, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStrokePublisher_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockStrokePublisher_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
//   - data []byte
func (_e *MockStrokePublisher_Expecter) Publish(ctx interface{}, sessionID interface{}, data interface{}) *MockStrokePublisher_Publish_Call {
	return &MockStrokePublisher_Publish_Call{Call: _e.mock.On("Publish", ctx, sessionID, data)}
}

func (_c *MockStrokePublisher_Publish_Call) Run(run func(ctx context.Context, sessionID string, data []byte)) *MockStrokePublisher_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte))
	})
	return _c
}

func (_c *MockStrokePublisher_Publish_Call) Return(_a0 error) *MockStrokePublisher_Publish_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStrokePublisher_Publish_Call) RunAndReturn(run func(context.Context, string, []byte) error) *MockStrokePublisher_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStrokePublisher creates a new instance of MockStrokePublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStrokePublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStrokePublisher {
	mock := &MockStrokePublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
